# Generated by Django 2.1 on 2018-10-19 02:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', models.CharField(max_length=100)),
                ('room_no', models.PositiveIntegerField()),
                ('availability', models.BooleanField(default=True)),
                ('occupancy', models.PositiveIntegerField()),
                ('floor', models.PositiveIntegerField()),
                ('occupation_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
