# Generated by Django 2.1 on 2018-10-25 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_auto_20181024_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='availability',
            field=models.IntegerField(default=1),
        ),
    ]
