# Generated by Django 2.1 on 2018-10-26 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_auto_20181025_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='block',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='floor',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='occupancy',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_no',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
