# Generated by Django 2.1 on 2018-10-28 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_auto_20181028_0521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='occupation_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
