# Generated by Django 2.1 on 2018-10-19 04:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('roll_no', models.CharField(max_length=10)),
                ('sex', models.CharField(max_length=6)),
                ('branch', models.CharField(max_length=50)),
                ('permanent_addr', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=10)),
                ('current_semester', models.PositiveSmallIntegerField()),
                ('doj', models.DateField(blank=True, null=True)),
                ('dog', models.DateField(blank=True, null=True)),
                ('roomID', models.ForeignKey(on_delete=models.SET(-1), to='rooms.Room')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
