# Generated by Django 2.1 on 2018-10-19 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentProfile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='roommate',
            field=models.ForeignKey(default=-1, on_delete=models.SET(-1), to='StudentProfile.Profile'),
            preserve_default=False,
        ),
    ]
