# Generated by Django 2.1 on 2018-10-19 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StudentProfile', '0002_profile_roommate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='roomID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rooms.Room'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='roommate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='StudentProfile.Profile'),
        ),
    ]
