# Generated by Django 2.1 on 2018-10-19 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudentProfile', '0004_academicdetails'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicdetails',
            options={'verbose_name_plural': 'Academic Details'},
        ),
    ]
