# Generated by Django 2.1 on 2018-10-19 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StudentProfile', '0005_auto_20181019_0523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicdetails',
            name='profile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='StudentProfile.Profile'),
        ),
    ]
