# Generated by Django 2.1 on 2018-10-24 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentProfile', '0016_auto_20181023_1116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answers',
            name='no',
        ),
        migrations.AddField(
            model_name='questions',
            name='ans1',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='ans2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='ans3',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='ans4',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Answers',
        ),
    ]
