# Generated by Django 2.1 on 2018-10-24 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudentProfile', '0018_auto_20181024_1054'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='quiz',
            unique_together={('profile', 'qno')},
        ),
    ]
