# Generated by Django 2.1 on 2018-10-24 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudentProfile', '0019_auto_20181024_1447'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='quiz',
            unique_together=set(),
        ),
    ]
