# Generated by Django 2.1 on 2018-10-24 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentProfile', '0021_auto_20181024_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='ans',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
