# Generated by Django 2.1 on 2018-10-24 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentProfile', '0022_auto_20181024_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='ans',
            field=models.CharField(default='1', max_length=10),
        ),
    ]
