# Generated by Django 2.1 on 2018-10-28 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StudentProfile', '0024_auto_20181024_1748'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hobbies', models.CharField(blank=True, max_length=200, null=True)),
                ('likes', models.CharField(blank=True, max_length=200, null=True)),
                ('dislikes', models.CharField(blank=True, max_length=200, null=True)),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='StudentProfile.Profile')),
            ],
            options={
                'verbose_name_plural': 'Hobbies',
            },
        ),
        migrations.RemoveField(
            model_name='hobbies',
            name='profile',
        ),
        migrations.DeleteModel(
            name='Hobbies',
        ),
    ]
