# Generated by Django 2.1 on 2018-10-28 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentProfile', '0025_auto_20181028_0758'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personality',
            options={'verbose_name_plural': 'Personality'},
        ),
        migrations.AlterField(
            model_name='quiz',
            name='ans',
            field=models.IntegerField(default=2),
        ),
    ]
