# Generated by Django 2.1 on 2018-10-28 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudentProfile', '0026_auto_20181028_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='similarity',
            name='quiz',
        ),
        migrations.DeleteModel(
            name='Similarity',
        ),
    ]
